### ISSUE TITLE
Neon syntax in Readme

### ISSUE THREAD

**Issue by TomasVotruba** [michalsvec/nette-opauth#7]
Use neon syntax (try http://ne-on.org/) if possible.

```
Strategy:
    Facebook:
        app_id: ''
        app_secret: ''
    Google:
        client_id: ''
        client_secret: ''
    Twitter:
        key: ''
        secret: ''
```
